---
- name: Create a virtual machine from a template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname | default(lookup('env', 'VMWARE_HOST')) }}"
    username: "{{ vcenter_username | default(lookup('env', 'VMWARE_USER')) }}"
    password: "{{ vcenter_password | default(lookup('env', 'VMWARE_PASSWORD')) }}"
    esxi_hostname: "{{ esxi_hostname }}"
    datacenter: "{{ datacenter }}"
    folder: /
    name: "{{ vm_name }}"
    state: poweredon
    template: "{{ vm_template }}"
    disk:
    - size_gb: "{{ vm_size }}"
      type: thin
      datastore: "{{ datastore }}"
    hardware:
      memory_mb: "{{ vm_memory | int * 1024 }}"
      num_cpus: "{{ vm_cpus }}"
      num_cpu_cores_per_socket: "{{ vm_cores_per_socket }}"
      scsi: paravirtual
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: True
      version: 12
      boot_firmware: "efi"
    networks:
    - name: "{{ vm_network }}"
    wait_for_ip_address: true
    validate_certs: false
    customization:
      hostname: "{{ vm_name }}"
  delegate_to: localhost
  register: deploy

- name: Add host to in-memory inventory
  add_host:
    name: "{{ deploy.instance.ipv4 }}"
    groups: created_vms
    ansible_user: "{{ ansible_user | default(lookup('env', 'ansible_user')) }}"
    ansible_sudo_pass: "{{ ansible_sudo_pass | default(lookup('env', 'ansible_sudo_pass')) }}"
